export { Header } from './00-header'
export { Hero } from './01-hero'
export { CodingAssistants } from './02-coding-assistants'
// Hidden components moved to ./hidden/ folder
export { FeaturesOne } from './04-features-one'
export { CreateBeautifulApps } from './create-beautiful-apps'
// export { VibeCodeConfidence } from './07-vibecode-confidence'
export { FeaturesBar } from './06-features-bar'
export { FAQ } from './08-faq'
export { FinalCTA } from './final-cta'
export { Footer } from './footer'